# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BMICalculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(433, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Calculate = QtWidgets.QPushButton(self.centralwidget)
        self.Calculate.setGeometry(QtCore.QRect(100, 470, 221, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Calculate.setFont(font)
        self.Calculate.setObjectName("Calculate")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(90, -10, 241, 131))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.input_height = QtWidgets.QLineEdit(self.centralwidget)
        self.input_height.setGeometry(QtCore.QRect(190, 140, 113, 22))
        self.input_height.setObjectName("input_height")
        self.input_weight = QtWidgets.QLineEdit(self.centralwidget)
        self.input_weight.setGeometry(QtCore.QRect(190, 240, 113, 22))
        self.input_weight.setObjectName("input_weight")
        self.Title_2 = QtWidgets.QLabel(self.centralwidget)
        self.Title_2.setGeometry(QtCore.QRect(80, 100, 121, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Title_2.setFont(font)
        self.Title_2.setObjectName("Title_2")
        self.Title_3 = QtWidgets.QLabel(self.centralwidget)
        self.Title_3.setGeometry(QtCore.QRect(80, 200, 121, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Title_3.setFont(font)
        self.Title_3.setObjectName("Title_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 350, 151, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_height = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_height.setGeometry(QtCore.QRect(310, 170, 93, 28))
        self.pushButton_height.setObjectName("pushButton_height")
        self.pushButton_weight = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_weight.setGeometry(QtCore.QRect(310, 270, 93, 28))
        self.pushButton_weight.setObjectName("pushButton_weight")
        self.weight_unit = QtWidgets.QLabel(self.centralwidget)
        self.weight_unit.setGeometry(QtCore.QRect(310, 220, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.weight_unit.setFont(font)
        self.weight_unit.setObjectName("weight_unit")
        self.height_unit = QtWidgets.QLabel(self.centralwidget)
        self.height_unit.setGeometry(QtCore.QRect(310, 120, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.height_unit.setFont(font)
        self.height_unit.setObjectName("height_unit")
        self.bmi_result = QtWidgets.QLabel(self.centralwidget)
        self.bmi_result.setGeometry(QtCore.QRect(190, 360, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bmi_result.setFont(font)
        self.bmi_result.setStyleSheet("background: white")
        self.bmi_result.setAlignment(QtCore.Qt.AlignCenter)
        self.bmi_result.setObjectName("bmi_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 433, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Calculate.clicked.connect(self.calculateBMI)
        self.pushButton_height.clicked.connect(self.toggleHeightUnit)
        self.pushButton_weight.clicked.connect(self.toggleWeightUnit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Calculate.setText(_translate("MainWindow", "Calculate BMI"))
        self.Title.setText(_translate("MainWindow", "BMI Calculator"))
        self.Title_2.setText(_translate("MainWindow", "Height"))
        self.Title_3.setText(_translate("MainWindow", "Weight"))
        self.label.setText(_translate("MainWindow", "Your BMI"))
        self.pushButton_height.setText(_translate("MainWindow", "Change Unit"))
        self.pushButton_weight.setText(_translate("MainWindow", "Change Unit"))
        self.weight_unit.setText(_translate("MainWindow", "KG"))
        self.height_unit.setText(_translate("MainWindow", "CM"))
        self.bmi_result.setText(_translate("MainWindow", "0.0"))
        
    def calculateBMI(self):
        font = QtGui.QFont()

        weight_input = self.input_weight.text()
        height_input = self.input_height.text()

        try:
            weight = float(weight_input)
            height = float(height_input)
        except:
            font.setPointSize(12)
            self.bmi_result.setFont(font)
            self.bmi_result.setText("Error Input")
            return

        if(self.height_unit.text() == "ft"):
            height = height * 30.48

        if(self.weight_unit.text() == "lbs"):
            weight = weight/2.205


        bmi = weight / (height/100*height/100)
        bmi = round(bmi,1)

        font.setPointSize(18)
        self.bmi_result.setFont(font)
        self.bmi_result.setText(str(bmi))
    
    def toggleHeightUnit(self):
        currentUnit = self.height_unit.text()

        if(currentUnit == "CM"):
            self.height_unit.setText("ft")
        else:
            self.height_unit.setText("CM")

    def toggleWeightUnit(self):
        currentUnit = self.weight_unit.text()

        if(currentUnit == "KG"):
            self.weight_unit.setText("lbs")
        else:
            self.weight_unit.setText("KG")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
